# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://hackwit.us"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-90684067-1"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "Hackwitus"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackWITus | 25/26 March 2017"
  description: "Come join Wentworth Institute of Technology's First Hackathon!"
  image:       "images/logo1.png"

# Event information.
event:
  name:        "HackWITus"
  description: "Wentworth Institute of Technology's first ever Hackathon"
  date:        "25 & 26 March 2017"
  location:    "Ira Allen Building, 540 Parker St, Boston MA 02120"
  #set this to true when schedule is ready
  schedule_ready: true

  # trust_badge:
  #   year:   "2017"  # season year
  #   region: "na"    # "na" or "eu"
  #   color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "b85972f8aa004c09989c02f10a874c51963e501106a36a676847b8490f34e226"
          redirect_uri: "https://www.eventbrite.com/e/hackwitus-tickets-31398465656?aff=eac2"
      - text: "Interested in sponsoring us?"
        href: "mailto:sponsorship@hackwit.us"

  about:
    description: >
      WE DON'T JUST STOP AT IMAGINATION; <br />
      WE BUILD, CREATE AND DEVELOP. <br />
      JOIN US!

  schedule:
    - title: "Saturday, March 25th 2017"
      events:
        - time: "9 AM"
          activity: "Open Registration"
        - time: "10 AM"
          activity: "Opening Ceremony"
        - time: "12 PM"
          activity: "Hacking Begin"
        - time: "1 PM"
          activity: "Lunch"
        - time: "7 PM"
          activity: "Dinner"
    - title: "Sunday, March 26th 2017"
      events:
        - time: "12 AM"
          activity: "Midnight Snack"
        - time: "7 AM"
          activity: "Breakfast"
        - time: "12 PM"
          activity: "Hacking End"
        - time: "1 PM"
          activity: "Lunch"
        - time: "2 PM"
          activity: "Demo"
        - time: "3 PM"
          activity: "Closing Ceremony"

  # Info Sections
  info:
    sections:
      - image: "images/pic01.jpg"
        icon: "fa-code"
        title: "WHAT IS A HACKATHON?"
        isRight: true
        description: >
          A hackathon is an invention marathon. Students come together to build cool software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
      - image: "images/pic02.jpg"
        icon: "fa-users"
        title: "WHO CAN ATTEND?"
        isRight: false
        description: >
          Any students who are currently enrolled at a college/university or have graduated within the past 12 months are eligible to attend. Plus, it's free!
      - image: "images/pic03.jpg"
        icon: "fa-question"
        title: "WHAT SHOULD I BRING?"
        isRight: true
        description: >
          Bring anything you'll need to stay overnight, as well as any technology you plan on using. We'll provide some stuff, but you can still bring your own!
      - image: "images/pic04.jpg"
        icon: "fa-map-marker"
        title: "WHERE/WHEN IS IT?"
        isRight: false
        description: >
          Wentworth Institute of Technology, the Ira Allen Building, 540 Parker St, Boston MA 02120. <br /> March 25th-26th, 2017.


  # Frequently asked questions.
  faq:
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending this hackathon is free.
    - question: "Do I need any special skills to attend or compete?"
      answer: >
        No, but some skills will help! Hackathons are primarily attended by people looking to pick up or improve new skills, so if you’re totally new to all of this that’s okay! We’re happy to help provide learning resources for you to take advantage of.
    - question: "What are the rules of this competition?"
      answer: >
        Participants will all begin the event at the same time, and must start their projects from scratch. In addition, all participants must follow the [MLH Code of Conduct](https://static.mlh.io/docs/mlh-code-of-conduct.pdf), which will be enforced.
    - question: "What sort of projects can be entered?"
      answer: >
        Any original technical project you can think of and create will be accepted.
    - question: "What will be provided for participants?"
      answer: >
        Food and snacks will be provided, as well as some educational, technical, and hardware resources. However, you are welcome to bring or purchase your own! We also recommend that you bring anything you may need to more comfortably stay overnight.
    # - question: "What is Major League Hacking?"
    #   answer: >
    #     Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
    #     We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "What if there is a change of plans or emergency?"
      answer: >
        For a change of plans, we will send an email to the email address that you give us when you sign up. You are also welcome to give us a safety contact so that in the event of an emergency we can get in touch with that individual.
    - question: "Will there be travel reimbursements?"
      answer: >
        We cannot offer travel reimbursements at this time.

  #Sponsor Section
  sponsor:
    affiliate:
      title: "Affiliates"
      description:
      affiliates:
        - title: "Wentworth Institute of Technology"
          logo: "images/sponsor_affiliates/wentworth.png"
        - title: "Wentworth Computer Science Society"
          logo: "images/sponsor_affiliates/wentworthcss.png"
        - title: "Association for Computing Machinery"
          logo: "images/sponsor_affiliates/acm.png"
        - title: "Major League Hacking"
          logo: "images/sponsor_affiliates/mlh.png"
    platinum:
      title: "Platinum Sponsors"
      sponsors:
        - title:
          logo:
          description:
    gold:
      title: "Gold Sponsors"
      sponsors:
        - title: IEEE
          logo: images/sponsor_affiliates/ieee.png
        - title: CVGC
          logo: images/sponsor_affiliates/cvgc.png
    silver:
      title: "Silver Sponsors"
      sponsors:
        - title: Wentworth Leadership Institute
          logo: images/sponsor_affiliates/leadership_institute.png
        - title: Douglas D. Schumann Library and Learning Commons
          logo: images/sponsor_affiliates/library.png
        - title: 4 Purpose Energy Drink
          logo: images/sponsor_affiliates/energy.jpg
    bronze:
      title: "Bronze Sponsors"
      sponsors:
        - title:
          logo:

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thanks for registering! You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
